<a href="https://colab.research.google.com/github/shivampandey781/fullcode/blob/main/RITassesment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=[2,3,7,2]
print("a =",a)

a = [2, 3, 7, 2]


In [4]:
A=[[1,3,7,2],[5,8,-9,0],[6,-7,11,12]]
print("A =",A)

A = [[1, 3, 7, 2], [5, 8, -9, 0], [6, -7, 11, 12]]


In [9]:
import numpy as np

a=np.array([[1],[3],[7],[2]])
print("a =",a)

A = np.array([[1, 3, 7, 2], [5, 8, -9, 0],[6, -7, 11, 12]])
print("A =", A)

a = [[1]
 [3]
 [7]
 [2]]
A = [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [10]:
import numpy as np
a = np.array([[1],[3],[7],[2]])
print("a =", a) 

A = np.matrix([[1, 3, 7, 2], [5, 8, -9, 0],[6, -7, 11, 12]])
print("A =", A)

a = [[1]
 [3]
 [7]
 [2]]
A = [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [11]:
import numpy as np
A = np.matrix([[0, 1], [-2, -3]])
B = np.matrix([[1, 0], [3, -2]])
C = A + B
print("A+B =", C)
C = A - B
print("A-B =", C)
C = A * B
print("A*B =", C

SyntaxError: ignored

In [12]:
import numpy as np
A = np.array([[0, 1], [-2, -3]])
B = np.array([[1, 0], [3, -2]])
C = A + B

print("A+B =", C)
C = A - B

print("A-B =", C)
C = A * B

print("A*B =", C) # Not Working!, only elementwise 
Multiplication!
#Working Alternative 1

C = A.dot(B)
print("A*B =", C)
#Working Alternative 2

C = np.dot(A,B)
print("A*B =", C)
#Working Alternative 3

C = np.mat(A) * np.mat(B)
print("A*B =", C)
#Working Alternative 4

C = np.matmul(A,B)
print("A*B =", C)

SyntaxError: ignored

In [13]:
import numpy as np
A = np.array([[1, 5, 3], [4, 6, 6],[3, 8, 9]])
B = np.array([[1, 5, 3, 4], [4, 5, 7, 8],[7, 8, 9, 3]])
C = np.array([[1], [4],[3]])
D = np.array([[1, 5, 3]])
M = np.matmul(A,B)
print("M=", M)

#M = np.matmul(B,A) # Not Working!

M = np.matmul(A,C)
print("M=", M)

#M = np.matmul(C,A) # Not Working!
M = np.matmul(C,D)
print("M=", M)

M = np.matmul(D,C)
print("M=", M)

M= [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]
M= [[30]
 [46]
 [62]]
M= [[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]
M= [[30]]


In [14]:
import numpy as np
A = np.array([[1, 3, 7, 2], [5, 8, -9, 0],[6, -7, 11, 12]])
print("A="); print(A)
Atr = np.transpose(A)
print("Transpose of A="); print(Atr)
B = np.array([[1, 5], [4, 5],[3, 2],[7, 8]])
print("B="); print(B)
Btr = np.transpose(B)
print("Transpose of B="); print(Btr)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]
Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


In [15]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2], [3, 4]])
Adet = la.det(A)
print(Adet)
B = np.array([[-1, 3, 0],[2, 1, -5],[1, 4, -2]])
Bdet = la.det(B)
print(Bdet)

-2.0000000000000004
-21.00000000000001


In [16]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2], 
[3, 4]])
Ainv = la.inv(A)
print(Adet)
B = np.array([[-1, 3, 0],
[2, 1, -5],
[1, 4, -2]])
Binv = la.inv(B)
print(Binv)

-2.0000000000000004
[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


In [17]:
import numpy as np
import numpy.linalg as la
A = np.array([[0, 1], [-2, -3]])
Aeig, v = la.eig(A)
print(Aeig)

[-1. -2.]


In [18]:
import numpy as np
A = np.array([[0, 1], [-2, -3]])
B = np.array([[1, 0], [3, -2]])
C = np.array([[1, 1], [1, -5]])
print("AB Not Equal BA")
L = np.matmul(A,B)
print("L=");print(L)
R = np.matmul(B,A)
print("R=");print(R)
print("A(BC) = (AB)C")
L = np.matmul(A,np.matmul(B,C))
print("L=");print(L)
R = np.matmul(np.matmul(A,B),C)
print("R=");print(R)

AB Not Equal BA
L=
[[  3  -2]
 [-11   6]]
R=
[[0 1]
 [4 9]]
A(BC) = (AB)C
L=
[[  1  13]
 [ -5 -41]]
R=
[[  1  13]
 [ -5 -41]]


In [19]:
import numpy as np
A = np.array([[0, 1], [-2, -3]])
B = np.array([[1, 0], [3, -2]])
C = np.array([[1, 1], [1, -5]])
print("(A+B)C = AC + BC")
L = np.matmul(A+B,C)
print("L=");print(L)
R = np.matmul(A,C) + np.matmul(B,C)
print("R=");print(R)
print("AA^(-1) = A^(-1)A = I")
L = np.matmul(A, la.inv(A))
print("L=");print(L)
R = np.matmul(la.inv(A),A)
print("R=");print(R)

(A+B)C = AC + BC
L=
[[ 2 -4]
 [-4 26]]
R=
[[ 2 -4]
 [-4 26]]
AA^(-1) = A^(-1)A = I
L=
[[1. 0.]
 [0. 1.]]
R=
[[1. 0.]
 [0. 1.]]


In [20]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
Ainv = la.inv(A)
x = Ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]


In [21]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
x = np.linalg.solve(A, b)
print(x)

[[-4. ]
 [ 4.5]]


In [23]:
import numpy as np
A = np.array([[1, 2], [3, 4],[7, 8]])
b = np.array([[5],[6],[9]])
x = np.linalg.lstsq(A, b, rcond=None)[0]
print(x)

[[-3.5       ]
 [ 4.17857143]]
